name: Pull Request Check

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper validation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-gi python3-gi-cairo gir1.2-gtk-3.0 \
            libcairo2-dev pkg-config python3-dev wget fakeroot \
            libgtk-3-dev libglib2.0-dev libpango1.0-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate Python code
        run: |
          pip install flake8
          # Check for syntax errors and undefined names only
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build AppImage
        run: |
          # Create build directory
          mkdir -p build
          
          # Run the build script
          bash packaging/build_appimage.sh
          
          # Check if AppImage was created successfully
          if [ ! -f ControllerLaunch*.AppImage ]; then
            echo "Error: AppImage build failed!"
            exit 1
          fi
          
          echo "AppImage built successfully: $(ls ControllerLaunch*.AppImage)"
          
      - name: Run validation script
        run: |
          # Run validation if it exists
          if [ -f "packaging/validate_build.sh" ]; then
            bash packaging/validate_build.sh
          fi
          
          # Run Python validation if it exists
          if [ -f "packaging/validate_modules.py" ]; then
            python packaging/validate_modules.py
          fi
